server.port=8080

# The maximum allowed size for uploaded files.
spring.servlet.multipart.max-file-size=5MB
# The maximum allowed size for a multipart/form-data request.
spring.servlet.multipart.max-request-size=10MB

# Property used to configure the directory where files will be stored.
storage.location=uploads
