package com.example.eurekadiscoveryclient.model;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Unit tests for the {@link ServiceInfo} domain record.
 *
 * <p>These tests verify the logic of the convenience factory method and
 * the derived {@code displayLabel()} method. No Spring context is started —
 * records are plain Java objects that can be tested directly.
 */
@DisplayName("ServiceInfo")
class ServiceInfoTest {

    // =========================================================================
    // ServiceInfo.of() factory method
    // =========================================================================

    @Nested
    @DisplayName("of() factory method")
    class OfFactory {

        @Test
        @DisplayName("constructs a ServiceInfo with correct URI derived from host and port")
        void shouldDeriveUriFromHostAndPort() {
            // Act
            ServiceInfo info = ServiceInfo.of("ORDER-SERVICE", "order:1", "host1", 8081);

            // Assert: URI is constructed as http://host:port
            assertThat(info.serviceId()).isEqualTo("ORDER-SERVICE");
            assertThat(info.instanceId()).isEqualTo("order:1");
            assertThat(info.host()).isEqualTo("host1");
            assertThat(info.port()).isEqualTo(8081);
            assertThat(info.uri()).isEqualTo("http://host1:8081");
        }

        @Test
        @DisplayName("constructs a ServiceInfo with port 80 correctly")
        void shouldWorkWithPort80() {
            ServiceInfo info = ServiceInfo.of("WEB-SERVICE", "web:1", "webhost", 80);

            assertThat(info.uri()).isEqualTo("http://webhost:80");
        }
    }

    // =========================================================================
    // displayLabel()
    // =========================================================================

    @Nested
    @DisplayName("displayLabel()")
    class DisplayLabel {

        @Test
        @DisplayName("returns a label combining serviceId and instanceId")
        void shouldCombineServiceIdAndInstanceId() {
            // Arrange
            ServiceInfo info = ServiceInfo.of("PAYMENT-SERVICE", "payment-host:PAYMENT-SERVICE:9090",
                    "payment-host", 9090);

            // Act
            String label = info.displayLabel();

            // Assert: format is "serviceId (instanceId)"
            assertThat(label).isEqualTo(
                    "PAYMENT-SERVICE (payment-host:PAYMENT-SERVICE:9090)");
        }

        @Test
        @DisplayName("displayLabel uses the raw serviceId value without modification")
        void shouldUseRawServiceId() {
            ServiceInfo info = new ServiceInfo("my-service", "my-service:1",
                    "localhost", 8080, "http://localhost:8080");

            assertThat(info.displayLabel()).startsWith("my-service");
        }
    }

    // =========================================================================
    // Record equality (auto-generated by Java records)
    // =========================================================================

    @Nested
    @DisplayName("record equality")
    class Equality {

        @Test
        @DisplayName("two ServiceInfo records with the same values are equal")
        void twoRecordsWithSameValuesShouldBeEqual() {
            ServiceInfo a = new ServiceInfo("SVC", "svc:1", "host", 8080, "http://host:8080");
            ServiceInfo b = new ServiceInfo("SVC", "svc:1", "host", 8080, "http://host:8080");

            assertThat(a).isEqualTo(b);
            assertThat(a.hashCode()).isEqualTo(b.hashCode());
        }

        @Test
        @DisplayName("two ServiceInfo records with different ports are not equal")
        void twoRecordsWithDifferentPortsShouldNotBeEqual() {
            ServiceInfo a = new ServiceInfo("SVC", "svc:1", "host", 8080, "http://host:8080");
            ServiceInfo b = new ServiceInfo("SVC", "svc:1", "host", 9090, "http://host:9090");

            assertThat(a).isNotEqualTo(b);
        }
    }
}
