package com.example.grpcclient.domain;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * JPA entity representing an order in the system.
 *
 * <p>An order captures:
 * <ul>
 *   <li>The customer who placed it.</li>
 *   <li>One or more {@link OrderLineItem}s (the products and quantities).</li>
 *   <li>The total monetary amount.</li>
 *   <li>The current lifecycle {@link OrderStatus}.</li>
 *   <li>The timestamp when it was created.</li>
 * </ul>
 *
 * <p>The order ID is a client-friendly UUID string rather than an auto-increment
 * integer, making it safe to reference in URLs and logs without exposing
 * internal database sequence values.
 *
 * <p>This entity is the persistence layer model. The corresponding protobuf
 * message ({@code Order} in order_service.proto) is the wire-transfer representation
 * used on the gRPC boundary — they are deliberately kept separate.
 */
@Entity
@Table(name = "orders")
public class Order {

    /**
     * UUID string used as the primary key.
     * Generated by the service layer using {@link java.util.UUID#randomUUID()}.
     * Not auto-generated by the database — we control the ID format.
     */
    @Id
    @Column(name = "order_id", nullable = false, length = 36)
    private String orderId;

    /**
     * Customer identifier who placed the order.
     */
    @Column(nullable = false, length = 100)
    private String customerId;

    /**
     * Current lifecycle status of the order.
     * Stored as a VARCHAR string for readability in the database.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private OrderStatus status;

    /**
     * Total monetary amount of the order in USD.
     * Computed as the sum of (quantity * unitPrice) across all line items.
     */
    @Column(nullable = false)
    private Double totalAmount;

    /**
     * Timestamp when the order was created.
     */
    @Column(nullable = false)
    private LocalDateTime createdAt;

    /**
     * The line items (products) included in this order.
     *
     * <p>CascadeType.ALL — all JPA lifecycle operations (persist, merge, remove, etc.)
     *   cascade from the Order parent to its child OrderLineItems. This means saving
     *   an Order automatically saves its line items too.
     *
     * <p>FetchType.LAZY — line items are only loaded from the database when accessed,
     *   not eagerly on every Order fetch. This prevents N+1 query issues.
     *
     * <p>orphanRemoval = true — if a line item is removed from the items list,
     *   it is automatically deleted from the database.
     */
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL,
               fetch = FetchType.EAGER, orphanRemoval = true)
    private List<OrderLineItem> items = new ArrayList<>();

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /** JPA requires a no-arg constructor. */
    protected Order() {}

    /**
     * Full constructor used by the service layer when creating new orders.
     *
     * @param orderId     the UUID string order identifier
     * @param customerId  the customer placing the order
     * @param status      initial order status (typically PENDING)
     * @param totalAmount total amount in USD
     * @param createdAt   creation timestamp
     */
    public Order(String orderId, String customerId, OrderStatus status,
                 Double totalAmount, LocalDateTime createdAt) {
        this.orderId = orderId;
        this.customerId = customerId;
        this.status = status;
        this.totalAmount = totalAmount;
        this.createdAt = createdAt;
    }

    // -------------------------------------------------------------------------
    // Convenience method
    // -------------------------------------------------------------------------

    /**
     * Add a line item to this order and set the back-reference.
     *
     * <p>The back-reference (item.setOrder(this)) is required by JPA to correctly
     * populate the foreign key column in the order_line_items table.
     *
     * @param item the line item to add
     */
    public void addItem(OrderLineItem item) {
        item.setOrder(this);
        this.items.add(item);
    }

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    public String getOrderId() { return orderId; }

    public String getCustomerId() { return customerId; }
    public void setCustomerId(String customerId) { this.customerId = customerId; }

    public OrderStatus getStatus() { return status; }
    public void setStatus(OrderStatus status) { this.status = status; }

    public Double getTotalAmount() { return totalAmount; }
    public void setTotalAmount(Double totalAmount) { this.totalAmount = totalAmount; }

    public LocalDateTime getCreatedAt() { return createdAt; }

    public List<OrderLineItem> getItems() { return items; }
}
