# Custom application properties
app.name=My Spring Boot Utility
app.version=1.0.0
app.description=This is a sample app for demonstrating @ConfigurationProperties
app.developer.name=Fabian
app.developer.email=fabian@example.com
app.features.enabled=true
app.features.max-users=500
