spring.application.name=basic-error-handling

# Enable Spring MVC standard ProblemDetail formulation for RFC 7807 support
# even for unhandled core Spring MVC exceptions natively.
spring.mvc.problem-details.enabled=true
