package com.example.multitenancy.domain;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Positive;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * JPA entity representing a product belonging to a tenant.
 *
 * <p>In the schema-per-tenant multi-tenancy model, the {@code products} table
 * exists inside <em>each</em> tenant's schema (e.g., {@code tenant_alpha.products},
 * {@code tenant_beta.products}). Hibernate resolves the table name to the correct
 * schema via the active {@code search_path} set by
 * {@link com.example.multitenancy.tenant.TenantConnectionProvider}.</p>
 *
 * <p>Notice that there is no tenant discriminator column — isolation is enforced at
 * the schema level, not at the row level. This is the key advantage of the
 * schema-per-tenant approach: tenant data is physically separated.</p>
 */
@Entity
@Table(name = "products")
public class Product {

    /**
     * Surrogate primary key.
     *
     * <p>We use {@code IDENTITY} generation, which maps to PostgreSQL's
     * {@code BIGSERIAL} / {@code GENERATED BY DEFAULT AS IDENTITY} column.
     * Each tenant schema has its own independent sequence.</p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Human-readable product name.
     * Must not be blank; validated by {@link NotBlank} before persistence.
     */
    @NotBlank(message = "Product name must not be blank")
    @Column(nullable = false)
    private String name;

    /**
     * Optional text description of the product.
     */
    @Column(columnDefinition = "TEXT")
    private String description;

    /**
     * Price of the product.
     * Must be a positive value; stored with scale 2 (e.g., 9.99).
     */
    @Positive(message = "Price must be positive")
    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal price;

    /**
     * Available stock quantity. Must be zero or positive.
     * Mapped to the snake_case column {@code stock_quantity} in PostgreSQL.
     */
    @Column(name = "stock_quantity", nullable = false)
    private int stockQuantity;

    /**
     * UTC timestamp of when this product record was created.
     * Set automatically before insert via the {@link PrePersist} lifecycle callback.
     * Mapped to the snake_case column {@code created_at} in PostgreSQL.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * UTC timestamp of the last update to this product record.
     * Updated automatically before each merge via the {@link PreUpdate} lifecycle callback.
     * Mapped to the snake_case column {@code updated_at} in PostgreSQL.
     */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /**
     * Default constructor required by JPA.
     */
    public Product() {}

    /**
     * Convenience constructor for creating new products programmatically.
     *
     * @param name          product name (must not be blank)
     * @param description   optional product description
     * @param price         product price (must be positive)
     * @param stockQuantity available stock quantity
     */
    public Product(String name, String description, BigDecimal price, int stockQuantity) {
        this.name = name;
        this.description = description;
        this.price = price;
        this.stockQuantity = stockQuantity;
    }

    /**
     * JPA lifecycle callback: sets {@code createdAt} and {@code updatedAt}
     * to the current UTC time immediately before the first INSERT.
     */
    @PrePersist
    protected void onCreate() {
        Instant now = Instant.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * JPA lifecycle callback: refreshes {@code updatedAt} before every UPDATE.
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = Instant.now();
    }

    // -------------------------------------------------------------------------
    // Getters and setters
    // -------------------------------------------------------------------------

    /** @return the surrogate primary key, or {@code null} for a new (unpersisted) entity */
    public Long getId() { return id; }

    /** @return the product name */
    public String getName() { return name; }

    /** Sets the product name. @param name new name */
    public void setName(String name) { this.name = name; }

    /** @return the optional product description */
    public String getDescription() { return description; }

    /** Sets the product description. @param description new description */
    public void setDescription(String description) { this.description = description; }

    /** @return the product price */
    public BigDecimal getPrice() { return price; }

    /** Sets the product price. @param price new price (must be positive) */
    public void setPrice(BigDecimal price) { this.price = price; }

    /** @return the available stock quantity */
    public int getStockQuantity() { return stockQuantity; }

    /** Sets the stock quantity. @param stockQuantity new quantity */
    public void setStockQuantity(int stockQuantity) { this.stockQuantity = stockQuantity; }

    /** @return the UTC instant when this record was created */
    public Instant getCreatedAt() { return createdAt; }

    /** @return the UTC instant when this record was last updated */
    public Instant getUpdatedAt() { return updatedAt; }

    @Override
    public String toString() {
        return "Product{id=" + id + ", name='" + name + "', price=" + price +
               ", stockQuantity=" + stockQuantity + "}";
    }
}
