package com.example.camundabpm.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.Instant;

/**
 * JPA entity representing an e-commerce order managed by the Camunda fulfilment process.
 *
 * <p>Lifecycle:
 * <ol>
 *   <li>A client POSTs to /api/orders — an Order record is persisted with status PENDING.</li>
 *   <li>The Camunda process is started with the order ID as a process variable.</li>
 *   <li>Each Java delegate (inventory, payment, shipping, notification) updates the
 *       order status in this table as it completes its step.</li>
 *   <li>When the process ends (completed or failed), the final status is stored here.</li>
 * </ol>
 *
 * <p>The {@code processInstanceId} field links this order to its corresponding
 * Camunda process instance, enabling cross-reference between the business entity
 * and the workflow engine's runtime state.
 */
@Entity
@Table(name = "orders")
public class Order {

    /**
     * Primary key — auto-generated by the database (SERIAL / BIGSERIAL in PostgreSQL,
     * AUTO_INCREMENT in other databases). Long is used to support a large number of orders.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the customer who placed the order. Required field — validated at the API layer
     * via @NotBlank before the order is persisted.
     */
    @Column(name = "customer_name", nullable = false)
    private String customerName;

    /**
     * The name or description of the product being ordered (e.g., "Laptop Pro 15").
     */
    @Column(name = "product_name", nullable = false)
    private String productName;

    /**
     * The number of items ordered. Must be a positive integer (validated at the API layer).
     */
    @Column(name = "quantity", nullable = false)
    private Integer quantity;

    /**
     * The unit price of the product. Used by the PaymentProcessingDelegate to calculate
     * the total charge: totalAmount = quantity * unitPrice.
     */
    @Column(name = "unit_price", nullable = false, precision = 10, scale = 2)
    private BigDecimal unitPrice;

    /**
     * The total amount charged to the customer. Computed and stored by the
     * PaymentProcessingDelegate when processing payment.
     */
    @Column(name = "total_amount", precision = 10, scale = 2)
    private BigDecimal totalAmount;

    /**
     * The current status of the order in its fulfilment lifecycle.
     * Stored as a string (VARCHAR) in the database for readability.
     * Updated by each Java delegate as the Camunda process advances.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 30)
    private OrderStatus status;

    /**
     * The Camunda process instance ID assigned when the fulfilment process is started.
     * Null until the process is started. Used to correlate this order with the Camunda
     * runtime state (e.g., for querying process variables, task lists, or history).
     */
    @Column(name = "process_instance_id")
    private String processInstanceId;

    /**
     * Shipping tracking number assigned by the ShippingDelegate.
     * Null until the order has been shipped.
     */
    @Column(name = "tracking_number")
    private String trackingNumber;

    /**
     * Timestamp when the order was created (epoch milliseconds in UTC).
     * Set once at creation and never changed.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * Timestamp when the order was last updated.
     * Updated by each delegate as the order progresses through the process.
     */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /**
     * Error message recorded when the process fails.
     * Null for orders that complete successfully.
     */
    @Column(name = "error_message", length = 500)
    private String errorMessage;

    /** Default no-arg constructor required by JPA. */
    protected Order() {}

    /**
     * Creates a new order with PENDING status and current timestamps.
     *
     * @param customerName the name of the customer placing the order
     * @param productName  the product being ordered
     * @param quantity     the number of items ordered
     * @param unitPrice    the price per unit
     */
    public Order(String customerName, String productName, Integer quantity, BigDecimal unitPrice) {
        this.customerName = customerName;
        this.productName = productName;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
        this.status = OrderStatus.PENDING;
        this.createdAt = Instant.now();
        this.updatedAt = Instant.now();
    }

    // -------------------------------------------------------------------------
    // Getters and setters
    // -------------------------------------------------------------------------

    public Long getId() {
        return id;
    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    public OrderStatus getStatus() {
        return status;
    }

    public void setStatus(OrderStatus status) {
        this.status = status;
        this.updatedAt = Instant.now();
    }

    public String getProcessInstanceId() {
        return processInstanceId;
    }

    public void setProcessInstanceId(String processInstanceId) {
        this.processInstanceId = processInstanceId;
    }

    public String getTrackingNumber() {
        return trackingNumber;
    }

    public void setTrackingNumber(String trackingNumber) {
        this.trackingNumber = trackingNumber;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public String getErrorMessage() {
        return errorMessage;
    }

    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }
}
