spring.application.name=environment-variable-config

# Application specific properties
# These properties act as defaults and can be overridden by environment variables 
# matching the exact syntax or upper snake case (e.g., APP_NAME).
app.name=Local Environment Variable App
