package com.example.cqrs.command.api;

import org.axonframework.modelling.command.TargetAggregateIdentifier;

import java.math.BigDecimal;

/**
 * Command to place (create) a new order.
 *
 * <p>In CQRS, a <em>command</em> expresses an <strong>intent</strong> to change system state.
 * Commands are named in the imperative mood (PlaceOrder, ConfirmOrder, …).
 *
 * <p>The {@link TargetAggregateIdentifier} annotation tells the Axon {@code CommandBus}
 * which aggregate instance this command is directed to. Axon uses the value of this field
 * to look up (or create) the correct {@code OrderAggregate} from the event store.
 *
 * <p>Commands are immutable value objects — we use Java {@code record}s to enforce this.
 *
 * @param orderId   unique identifier for the new order (UUID string)
 * @param productId identifier of the product being ordered
 * @param quantity  number of units to order (must be positive)
 * @param unitPrice price per unit (must be positive)
 */
public record PlaceOrderCommand(

        /**
         * Axon uses this field to route the command to the correct aggregate instance.
         * For a creation command the value is generated by the caller (REST controller)
         * before sending — this is the "client-assigned ID" pattern.
         */
        @TargetAggregateIdentifier
        String orderId,

        String productId,
        int quantity,
        BigDecimal unitPrice
) {}
